const startersData = [
  {
    "_id": "5f03d0d425a0ed78961ed591",
    "menuItemName": "Peach & Cucumber Gazpacho",
    "type": "starter",
    "isSpecial": false,
    "image": "pcGazpacho",
    "ingredients": "Peaches, cucumber, onion, garlic, almonds, honey, sherry, herbs, olive oil, baguette",
    "idAuto": null,
    "price": "$6/$10",
    "itemOption": null,
    "specialPrice": null,
    "customOption": null
  },
  {
    "_id": "5f03d0d425a0ed78961ed592",
    "menuItemName": "Veggie Spring Rolls (V)",
    "type": "starter",
    "isSpecial": false,
    "image": "veggieSpring",
    "ingredients": "Three fried vegetable spring rolls, black beans, cheddar-jack cheese, carrots, cabbage, sweet garlic-chili dipping sauce",
    "idAuto": null,
    "price": "$9",
    "itemOption": null,
    "specialPrice": null,
    "customOption": null
  },
  {
    "_id": "5f03d0d425a0ed78961ed593",
    "menuItemName": "Hobnob Cob (V, GF)",
    "type": "starter",
    "isSpecial": false,
    "image": "hobnobCob",
    "ingredients": "Grilled corn, paprika mayo, cilantro-lime crema, cotija cheese, lime, fresh cilantro",
    "idAuto": null,
    "price": "$10",
    "itemOption": null,
    "specialPrice": null,
    "customOption": null
  },
  {
    "_id": "5f03d0d425a0ed78961ed594",
    "menuItemName": "Buffalo Wings (GF)",
    "type": "starter",
    "isSpecial": false,
    "image": "buffaloWings",
    "ingredients": "Seared beef tenderloin, iceberg lettuce, cucumber, red onion, scallion, applewood smoked bacon, tomatoes, blue cheese dressing, balsamic glaze",
    "idAuto": null,
    "price": "$14/$25",
    "itemOption": null,
    "specialPrice": null,
    "customOption": null
  },
  {
    "_id": "5f03d0d425a0ed78961ed595",
    "menuItemName": "Steak Wedge Salad (GF)",
    "type": "starter",
    "isSpecial": false,
    "image": "steakWedgeSalad",
    "ingredients": "Seared beef tenderloin, iceberg lettuce, cucumber, red onion, scallion, applewood smoked bacon, tomatoes, blue cheese dressing, balsamic glaze",
    "idAuto": null,
    "price": "$14/$25",
    "itemOption": null,
    "specialPrice": null,
    "customOption": null
  },
  {
    "_id": "5f03d0d425a0ed78961ed596",
    "menuItemName": "Strawberry Goat Cheese Salad (V, GF)",
    "type": "starter",
    "isSpecial": false,
    "image": "strawberryGoatCheese",
    "ingredients": "Mixed greens, fresh strawberries, candied walnuts, goat cheese, red onion, avocado, balsamic vinaigrette",
    "idAuto": null,
    "price": "$10/$18",
    "itemOption": null,
    "specialPrice": null,
    "customOption": null
  },
  {
    "_id": "5f03d0d425a0ed78961ed597",
    "menuItemName": "Avocado Caprese Salad (V, GF)",
    "type": "starter",
    "isSpecial": false,
    "image": "avocadoCaprese",
    "ingredients": "Avocado, burrata, tomato, peach, arugula pesto, toasted almonds, balsamic vinaigrette",
    "idAuto": null,
    "price": "$12/$20",
    "itemOption": null,
    "specialPrice": null,
    "customOption": null
  },
  {
    "_id": "5f03d0d425a0ed78961ed598",
    "menuItemName": "Fried Chicken Cobb Salad",
    "type": "starter",
    "isSpecial": false,
    "image": "friedChickenCobb",
    "ingredients": "Fried chicken breast, mixed greens, avocado, sweet corn, tomato, applewood smoked bacon, chopped egg, blue cheese crumbles, buttermilk ranch dressing",
    "idAuto": null,
    "price": "$14/$25",
    "itemOption": null,
    "specialPrice": null,
    "customOption": null
  },
  {
    "_id": "5f03d17225a0ed78961ed599",
    "menuItemName": "Peach & Cucumber Gazpacho",
    "type": "starter",
    "isSpecial": false,
    "image": "pcGazpacho",
    "ingredients": "Peaches, cucumber, onion, garlic, almonds, honey, sherry, herbs, olive oil, baguette",
    "idAuto": null,
    "price": "$6/$10",
    "itemOption": null,
    "specialPrice": null,
    "customOption": null
  },
  {
    "_id": "5f03d17225a0ed78961ed59a",
    "menuItemName": "Veggie Spring Rolls (V)",
    "type": "starter",
    "isSpecial": false,
    "image": "veggieSpring",
    "ingredients": "Three fried vegetable spring rolls, black beans, cheddar-jack cheese, carrots, cabbage, sweet garlic-chili dipping sauce",
    "idAuto": null,
    "price": "$9",
    "itemOption": null,
    "specialPrice": null,
    "customOption": null
  }
];

export default startersData;
